!
!  DNNF90
!  Copyright (C) 2026  Fumihiro Imoto
!
!  This file (multi_index_bell_module.f90) is part of DNNF90.
!
!  DNNF90 is free software released under the MIT License.
!  You should have received a copy of the MIT License (file LICENSE
!  in the root directory of this distribution) along with DNNF90.
!  If not, see <https://opensource.org/licenses/MIT>.
!
!  DNNF90 is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  MIT License for more details.
!
! Multi-index tables for high-order derivative (HOD) propagation.
!
! Implements the bookkeeping of the note "4-variable input / up to 7th-order
! partial derivatives" (Appendix-D notation of Imoto et al., PRR 3, 033198):
!   - graded enumeration of multi-indices alpha with |alpha| <= K
!     (order matches Python itertools.combinations_with_replacement, so data
!      files generated by either side agree column-by-column)
!   - multi-index partial Bell polynomial tables B_{alpha,q} in the
!     unordered-partition normalisation:
!         B_{alpha,q} = sum over multisets {beta_s^{m_s}} of
!                       alpha! * prod_s 1/( m_s! * (beta_s!)^{m_s} )
!     (the ordered-sum reading double-counts by q!/prod m_s! ; correction E1)
!   - tanh derivatives sigma^{(q)}, q <= K+1, via the closed polynomial
!     recursion P_0(t)=t, P_{q+1}(t) = (1-t^2) P_q'(t), t = tanh(a)
!   - optional restriction to the downward closure of a user-supplied
!     downward closure (all gamma <= alpha for some seed alpha)
!
! Conventions: index ia=1 is alpha=0;  B_{0,0}=1, B_{alpha,0}=0 (alpha>0).
!
MODULE multi_index_bell_module

  implicit none

  PRIVATE
  PUBLIC :: init_hod_tables, tanh_derivs_hod, write_alpha_order, alpha_index
  PUBLIC :: hod_tables_ready, reset_hod_tables
  PUBLIC :: tabset_t, tabset_init, tabset_from_current, tabset_free, tanh_derivs_ts
  PUBLIC :: act_derivs_ts, sin_derivs, erf_derivs, besj0_derivs, besj1_derivs
  PUBLIC :: HOD_D0, HOD_KMAX, NUM_alpha
  PUBLIC :: alpha_list, alpha_deg, ind_e1
  PUBLIC :: bell_num, bell_start, bell_coef, bell_part
  PUBLIC :: pair_start, pair_num, pair_ia, pair_id, pair_binom
  PUBLIC :: fq_start, fq_num, fq_ib, fq_id, fq_c

  !> One complete, independent table set: everything the evaluation and
  !! training kernels read.  Built as a deep copy (snapshot) of the
  !! module level tables, so several sets with different D0 and K can
  !! coexist in one process, one per network family (for example one per
  !! element species with its own descriptor count).
  TYPE :: tabset_t
     integer :: d0 = 0, kmax = 0, na = 0
     !> 0 = tanh, 1 = sin, 2 = erf.  The engine consumes only sigma^(q),
     !! so this is the one place the choice of activation enters.
     integer,allocatable :: alpha_list(:,:)
     integer,allocatable :: alpha_deg(:)
     integer,allocatable :: ind_e1(:)
     integer,allocatable :: pair_start(:)
     integer,allocatable :: pair_num(:)
     integer,allocatable :: pair_ia(:)
     integer,allocatable :: pair_id(:)
     real(8),allocatable :: pair_binom(:)
     integer,allocatable :: fq_start(:,:)
     integer,allocatable :: fq_num(:,:)
     integer,allocatable :: fq_ib(:)
     integer,allocatable :: fq_id(:)
     real(8),allocatable :: fq_c(:)
     real(8),allocatable :: tpc(:,:)  ! tanh derivative polynomials
     !> Which activation this table set propagates.  The Bell machinery
     !! consumes only sigma^(q), so the activation enters here and
     !! nowhere else: 0 = tanh, 1 = sin, 2 = erf.
     integer :: iact = 0
  END TYPE tabset_t

  logical :: hod_tables_ready = .false.
  integer :: HOD_D0 = 0        ! number of input variables ( = ndim(1) )
  integer :: HOD_KMAX = 0      ! maximum derivative order K
  integer :: NUM_alpha = 0     ! number of multi-indices carried (incl. alpha=0)

  integer,allocatable :: alpha_list(:,:)  ! (D0,NUM_alpha); ia=1 -> alpha=0
  integer,allocatable :: alpha_deg(:)     ! |alpha|
  integer,allocatable :: ind_e1(:)        ! (D0) index of the unit multi-index e_i
  integer,allocatable :: ind_diff(:,:)    ! (NUM_alpha,NUM_alpha) index of alpha-beta
  ! flattened (ia,ib) pair lists for the adjoint: for each ib>=2,
  ! all ia with ib <= ia, id = ind_diff(ia,ib), and the binomial factor
  integer,allocatable :: pair_start(:), pair_num(:)
  integer,allocatable :: pair_ia(:), pair_id(:)
  real(8),allocatable :: pair_binom(:)
  ! forward DP tables: Bell values via the convolution recurrence
  !   B(a,q) = (1/q) sum_b C(a,b) s_b B(a-b,q-1)
  ! entries for (ia,q>=2) keep only b with deg(a)-deg(b) >= q-1 and the
  ! 1/q factor is folded into the stored coefficient
  integer,allocatable :: fq_start(:,:), fq_num(:,:)
  integer,allocatable :: fq_ib(:), fq_id(:)
  real(8),allocatable :: fq_c(:)
                                          ! (0 unless beta <= alpha componentwise)
  real(8),allocatable :: binom_ab(:,:)    ! multi-binomial C(alpha,beta)

  ! Bell tables: for (ia,q) the terms are
  !   bell_coef(it) * prod_{ip=1..q} S( bell_part(ip,it) ),
  !   it = bell_start(ia,q) .. bell_start(ia,q)+bell_num(ia,q)-1
  integer,allocatable :: bell_num(:,:)    ! (NUM_alpha,1:KMAX)
  integer,allocatable :: bell_start(:,:)
  real(8),allocatable :: bell_coef(:)
  integer,allocatable :: bell_part(:,:)   ! (KMAX,total_terms)

  ! tanh derivative polynomials: sigma^{(q)}(a) = sum_i tanh_pc(i,q)*t**i
  real(8),allocatable :: tanh_pc(:,:)     ! (0:KMAX+2, 0:KMAX+1)

  ! internal
  ! Lookup of a multi-index by value.  A dense key table of size
  ! (K+1)**D0 would be exponential in the number of inputs and
  ! impossible for the descriptor counts of a force field
  ! (D0 = 50 to 100).  The multi-indices are instead kept in a
  ! lexicographic order and located by binary search, which costs
  ! O(D0 log |A|) per lookup and is used only while the tables are built.
  integer,allocatable :: lex_ord(:)       ! (NUM_alpha) lexicographic order
  real(8) :: fact_tab(0:16)

CONTAINS

  !=====================================================================
  SUBROUTINE init_hod_tables( D0, K, nseed, seed_alpha )
    implicit none
    integer,intent(IN) :: D0, K, nseed
    integer,intent(IN) :: seed_alpha(D0,*)  ! referenced only if nseed>0
    integer :: nfull, ia, ib, i, p, q, iv, is
    integer,allocatable :: afull(:,:)
    logical,allocatable :: incl(:)
    integer :: icount, nterm_max, nterm_tot
    integer,allocatable :: work_parts(:)
    real(8) :: rtmp

    if ( K < 1 .or. K > 15 ) then
       write(*,*) "init_hod_tables: K out of range:", K
       stop
    end if

    HOD_D0 = D0
    HOD_KMAX = K

    fact_tab(0) = 1.d0
    do i=1,16
       fact_tab(i) = fact_tab(i-1)*dble(i)
    end do

    !--- enumerate all multi-indices with |alpha| <= K (graded, CWR order)
    nfull = n_multi_indices( D0, K )
    allocate( afull(D0,nfull) )
    icount = 0
    do p=0,K
       call gen_cwr( D0, p, afull, nfull, icount )
    end do
    if ( icount /= nfull ) then
       write(*,*) "init_hod_tables: enumeration count mismatch", icount, nfull
       stop
    end if

    !--- optional restriction to the downward closure of the seed set
    allocate( incl(nfull) )
    if ( nseed > 0 ) then
       incl(:) = .false.
       do is=1,nseed
          if ( sum(seed_alpha(1:D0,is)) > K ) then
             write(*,*) "init_hod_tables: seed multi-index exceeds K"
             stop
          end if
          do ia=1,nfull
             if ( all( afull(1:D0,ia) <= seed_alpha(1:D0,is) ) ) incl(ia)=.true.
          end do
       end do
    else
       incl(:) = .true.
    end if

    NUM_alpha = count(incl)
    if ( allocated(alpha_list) ) then
       deallocate( alpha_list, alpha_deg, ind_e1 )
       if ( allocated(ind_diff) ) deallocate( ind_diff )
       if ( allocated(binom_ab) ) deallocate( binom_ab )
       if ( allocated(pair_start) ) deallocate( pair_start,pair_num,pair_ia,pair_id,pair_binom )
       if ( allocated(fq_start) ) deallocate( fq_start,fq_num,fq_ib,fq_id,fq_c )
       deallocate( bell_num, bell_start, bell_coef, bell_part, tanh_pc, lex_ord )
    end if
    allocate( alpha_list(D0,NUM_alpha), alpha_deg(NUM_alpha) )
    icount = 0
    do ia=1,nfull
       if ( incl(ia) ) then
          icount = icount+1
          alpha_list(:,icount) = afull(:,ia)
          alpha_deg(icount) = sum( afull(:,ia) )
       end if
    end do
    deallocate( afull, incl )
    if ( alpha_deg(1) /= 0 ) then
       write(*,*) "init_hod_tables: alpha=0 missing (empty closure?)"
       stop
    end if

    !--- lookup order for locating a multi-index by value
    allocate( lex_ord(NUM_alpha) )
    call build_lex_order

    !--- unit multi-indices e_i (0 if excluded by the closure)
    allocate( ind_e1(D0) ); ind_e1=0
    do ia=1,NUM_alpha
       if ( alpha_deg(ia)==1 ) then
          do iv=1,D0
             if ( alpha_list(iv,ia)==1 ) ind_e1(iv)=ia
          end do
       end if
    end do

    !--- ind_diff and multi-binomials
    allocate( ind_diff(NUM_alpha,NUM_alpha) ); ind_diff=0
    allocate( binom_ab(NUM_alpha,NUM_alpha) ); binom_ab=0.d0
    do ia=1,NUM_alpha
       do ib=1,NUM_alpha
          if ( all( alpha_list(:,ib) <= alpha_list(:,ia) ) ) then
             ind_diff(ia,ib) = find_alpha( alpha_list(:,ia)-alpha_list(:,ib) )
             rtmp = 1.d0
             do iv=1,D0
                rtmp = rtmp * fact_tab(alpha_list(iv,ia)) / &
                     ( fact_tab(alpha_list(iv,ib)) * fact_tab(alpha_list(iv,ia)-alpha_list(iv,ib)) )
             end do
             binom_ab(ia,ib) = rtmp
          end if
       end do
    end do

    !--- Bell polynomial tables (unordered partitions, nondecreasing part lists)
    ! The number of Bell terms was formerly capped by a hard constant.
    ! The cap is not reached by small cases but is exceeded by ordinary
    ! ones (six variables at order seven, for instance), which aborted the
    ! run with a message the user could do nothing about.  The terms are
    ! counted first and the tables are then allocated to the exact size,
    ! so the only limit left is the available memory.
    allocate( bell_num(NUM_alpha,K), bell_start(NUM_alpha,K) )
    bell_num=0; bell_start=0
    allocate( work_parts(K) )
    nterm_tot = 0
    do ia=2,NUM_alpha
       p = alpha_deg(ia)
       do q=1,p
          call bell_enum( ia, q, 1, 2, alpha_list(:,ia), work_parts, nterm_tot, .true. )
       end do
    end do
    nterm_max = max( nterm_tot, 1 )
    allocate( bell_coef(nterm_max), bell_part(K,nterm_max) )
    bell_coef=0.d0; bell_part=0
    nterm_tot = 0
    do ia=2,NUM_alpha
       p = alpha_deg(ia)
       do q=1,p
          bell_start(ia,q) = nterm_tot+1
          call bell_enum( ia, q, 1, 2, alpha_list(:,ia), work_parts, nterm_tot, .false. )
          bell_num(ia,q) = nterm_tot - bell_start(ia,q) + 1
       end do
    end do
    deallocate( work_parts )

    !--- adjoint pair tables: flatten the ib<=ia sparsity pattern
    allocate( pair_start(NUM_alpha), pair_num(NUM_alpha) )
    pair_num = 0
    do ib=2,NUM_alpha
       do ia=2,NUM_alpha
          if ( ind_diff(ia,ib) > 0 ) pair_num(ib) = pair_num(ib)+1
       end do
    end do
    ! pair_start(2) is only meaningful when a second multi-index exists.
    ! A closure seeded with the zero multi-index alone leaves NUM_alpha=1,
    ! and the unguarded assignment below then wrote one element past the
    ! end of the array: harmless under bounds checking, silent heap
    ! corruption in an optimized build.
    pair_start(1) = 1
    if ( NUM_alpha >= 2 ) pair_start(2) = 1
    do ib=3,NUM_alpha
       pair_start(ib) = pair_start(ib-1) + pair_num(ib-1)
    end do
    iv = sum( pair_num )
    allocate( pair_ia(iv), pair_id(iv), pair_binom(iv) )
    iv = 0
    do ib=2,NUM_alpha
       do ia=2,NUM_alpha
          if ( ind_diff(ia,ib) > 0 ) then
             iv = iv+1
             pair_ia(iv)    = ia
             pair_id(iv)    = ind_diff(ia,ib)
             pair_binom(iv) = binom_ab(ia,ib)
          end if
       end do
    end do

    !--- forward DP tables
    allocate( fq_start(NUM_alpha,2:max(K,2)), fq_num(NUM_alpha,2:max(K,2)) )
    fq_num = 0;  fq_start = 1      ! slots with fq_num=0 must still hold a
                                   ! defined bound, not whatever was on the heap
    iv = 0
    do ia=2,NUM_alpha
       p = alpha_deg(ia)
       do q=2,p
          do ib=2,NUM_alpha
             if ( ind_diff(ia,ib) > 0 ) then
                if ( p - alpha_deg(ib) >= q-1 ) iv = iv+1
             end if
          end do
       end do
    end do
    allocate( fq_ib(max(iv,1)), fq_id(max(iv,1)), fq_c(max(iv,1)) )
    iv = 0
    do ia=2,NUM_alpha
       p = alpha_deg(ia)
       do q=2,p
          fq_start(ia,q) = iv+1
          do ib=2,NUM_alpha
             if ( ind_diff(ia,ib) > 0 ) then
                if ( p - alpha_deg(ib) >= q-1 ) then
                   iv = iv+1
                   fq_ib(iv) = ib
                   fq_id(iv) = ind_diff(ia,ib)
                   fq_c(iv)  = binom_ab(ia,ib)/dble(q)
                end if
             end if
          end do
          fq_num(ia,q) = iv - fq_start(ia,q) + 1
       end do
    end do

    !--- tanh derivative polynomials up to order K+1
    call build_tanh_poly( K+1 )

    hod_tables_ready = .true.

    write(*,'(a)') "### init_hod_tables"
    write(*,'(a,i0,a,i0)') "###   D0=", D0, "  K=", K
    write(*,'(a,i0)') "###   NUM_alpha (multi-indices carried) = ", NUM_alpha
    write(*,'(a,i0)') "###   Bell table terms                  = ", nterm_tot
    if ( nseed>0 ) write(*,'(a,i0,a)') "###   restricted to closure of ", nseed, " seed indices"

    ! ind_diff and binom_ab are construction scaffolding only: the
    ! kernels read the flattened pair and fq lists.  They are O(|A|^2),
    ! which is 318 MB at |A| = 5151 (100 descriptors, order two), so
    ! they are released here instead of being kept for the run.
    deallocate( ind_diff, binom_ab )

  END SUBROUTINE init_hod_tables

  !=====================================================================
  ! ordered enumeration of nondecreasing part lists (i.e. multisets):
  ! parts(1) <= parts(2) <= ... <= parts(q), all deg>=1, sum = alpha(ia)
  RECURSIVE SUBROUTINE bell_enum( ia, q, depth, id_min, rem, parts, nterm, count_only )
    implicit none
    integer,intent(IN) :: ia, q, depth, id_min
    integer,intent(IN) :: rem(HOD_D0)
    integer,intent(INOUT) :: parts(HOD_KMAX)
    integer,intent(INOUT) :: nterm
    logical,intent(IN) :: count_only
    integer :: id, iv, m, ip
    integer :: rem_new(HOD_D0)
    real(8) :: coef

    do id=id_min,NUM_alpha
       if ( alpha_deg(id) < 1 ) cycle
       if ( alpha_deg(id) > sum(rem) - (q-depth) ) cycle   ! leave >=1 per slot
       if ( any( alpha_list(:,id) > rem ) ) cycle
       parts(depth) = id
       rem_new = rem - alpha_list(:,id)
       if ( depth == q ) then
          if ( all( rem_new == 0 ) ) then
             ! coefficient alpha! / prod_s ( m_s! * (beta_s!)^{m_s} )
             nterm = nterm+1
             if ( count_only ) cycle
             coef = 1.d0
             do iv=1,HOD_D0
                coef = coef * fact_tab( alpha_list(iv,ia) )
             end do
             ip = 1
             do while ( ip <= q )
                m = 1
                do while ( ip+m <= q )
                   if ( parts(ip+m) /= parts(ip) ) exit
                   m = m+1
                end do
                coef = coef / fact_tab(m)
                do iv=1,HOD_D0
                   coef = coef / ( fact_tab( alpha_list(iv,parts(ip)) )**m )
                end do
                ip = ip+m
             end do
             bell_coef(nterm) = coef
             bell_part(1:q,nterm) = parts(1:q)
          end if
       else
          call bell_enum( ia, q, depth+1, id, rem_new, parts, nterm, count_only )
       end if
    end do

  END SUBROUTINE bell_enum

  !=====================================================================
  SUBROUTINE build_tanh_poly( qmax )
    implicit none
    integer,intent(IN) :: qmax
    integer :: q, i
    real(8),allocatable :: dc(:)

    allocate( tanh_pc(0:qmax+1, 0:qmax) ); tanh_pc=0.d0
    tanh_pc(1,0) = 1.d0                    ! P_0(t) = t
    allocate( dc(0:qmax+1) )
    do q=0,qmax-1
       ! dP_q/dt
       dc = 0.d0
       do i=0,qmax
          dc(i) = dble(i+1)*tanh_pc(i+1,q)
       end do
       ! P_{q+1} = (1-t^2) * dP_q/dt
       do i=0,qmax+1
          tanh_pc(i,q+1) = dc(i)
          if ( i>=2 ) tanh_pc(i,q+1) = tanh_pc(i,q+1) - dc(i-2)
       end do
    end do
    deallocate( dc )

  END SUBROUTINE build_tanh_poly

  !=====================================================================
  ! d(q) = sigma^{(q)}(a), q=0..nq, for sigma = tanh
  SUBROUTINE tanh_derivs_hod( a, nq, d )
    implicit none
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8) :: t
    integer :: q, i

    t = tanh(a)
    do q=0,nq
       d(q) = tanh_pc(q+1,q)
       do i=q,0,-1
          d(q) = d(q)*t + tanh_pc(i,q)
       end do
    end do

  END SUBROUTINE tanh_derivs_hod

  !=====================================================================
  SUBROUTINE write_alpha_order( fname )
    implicit none
    character(*),intent(IN) :: fname
    integer,parameter :: uo=41
    integer :: ia
    character(32) :: cfmt

    ! One line per multi-index whatever D0 is: a fixed repeat count of ten
    ! made the record wrap for the descriptor counts a force field uses,
    ! and i0 keeps the index field from overflowing on a large set.
    write(cfmt,'("(i0,2x,i0,2x,",i0,"(1x,i0))")') HOD_D0
    open(uo,file=fname,status='replace')
    write(uo,'(a)') "# column order of high-order derivative targets"
    write(uo,'(a)') "# ia  |alpha|  alpha(1:D0)"
    do ia=1,NUM_alpha
       write(uo,cfmt) ia, alpha_deg(ia), alpha_list(1:HOD_D0,ia)
    end do
    close(uo)

  END SUBROUTINE write_alpha_order

  !=====================================================================
  ! index of a multi-index in the carried set (0 if not carried)
  INTEGER FUNCTION alpha_index( a )
    implicit none
    integer,intent(IN) :: a(HOD_D0)
    if ( any(a<0) .or. sum(a)>HOD_KMAX ) then
       alpha_index = 0
    else
       alpha_index = find_alpha( a )
    end if
  END FUNCTION alpha_index

  !=====================================================================
  !> Lexicographic order of the multi-indices (insertion into a sorted
  !! list; called once per table build).
  SUBROUTINE build_lex_order
    implicit none
    integer :: i, j, k
    do i=1,NUM_alpha
       lex_ord(i) = i
    end do
    do i=2,NUM_alpha
       k = lex_ord(i)
       j = i-1
       do while ( j >= 1 )
          if ( lex_less( alpha_list(:,lex_ord(j)), alpha_list(:,k) ) ) exit
          lex_ord(j+1) = lex_ord(j)
          j = j-1
       end do
       lex_ord(j+1) = k
    end do
  END SUBROUTINE build_lex_order

  LOGICAL FUNCTION lex_less( a, b )
    implicit none
    integer,intent(IN) :: a(:), b(:)
    integer :: i
    lex_less = .false.
    do i=1,size(a)
       if ( a(i) /= b(i) ) then
          lex_less = ( a(i) < b(i) );  return
       end if
    end do
  END FUNCTION lex_less

  !> Index of the multi-index a, or 0 if it is not carried.  Binary
  !! search over lex_ord; no table of size (K+1)**D0 is needed.
  INTEGER FUNCTION find_alpha( a )
    implicit none
    integer,intent(IN) :: a(:)
    integer :: lo, hi, mid, ic
    lo = 1;  hi = NUM_alpha
    do while ( lo <= hi )
       mid = (lo+hi)/2
       ic = lex_ord(mid)
       if ( all( alpha_list(:,ic) == a(1:HOD_D0) ) ) then
          find_alpha = ic;  return
       end if
       if ( lex_less( alpha_list(:,ic), a(1:HOD_D0) ) ) then
          lo = mid+1
       else
          hi = mid-1
       end if
    end do
    find_alpha = 0
  END FUNCTION find_alpha

  !> Number of multi-indices with |alpha| <= K in D0 variables,
  !! sum_p C(p+D0-1, p).
  !!
  !! The binomial is built incrementally, c <- c*(D0-1+i)/i, which is
  !! exact at every step because the partial product is C(D0-1+i, i).
  !! Forming the full numerator and denominator separately would
  !! overflow a 32-bit integer for D0 >= 13 and silently return a wrong
  !! size, so that the tables would be allocated too small.  Descriptor
  !! counts of
  !! 50 to 100 are normal for force fields, so the count is computed in
  !! 64-bit with an explicit range check.
  INTEGER FUNCTION n_multi_indices( D0, K )
    implicit none
    integer,intent(IN) :: D0, K
    integer :: p, i
    integer(8) :: c, tot
    tot = 0_8
    do p=0,K
       c = 1_8
       do i=1,p
          c = c*int(D0-1+i,8)/int(i,8)
       end do
       tot = tot + c
    end do
    if ( tot > int(huge(0)/2,8) ) then
       write(*,*) "n_multi_indices: the carried set is too large for a", &
                  " default integer:", tot
       write(*,*) "  D0 =", D0, "  K =", K, &
                  "  (restrict the set with seed multi-indices)"
       stop
    end if
    n_multi_indices = int( tot )
  END FUNCTION n_multi_indices

  ! degree-p multi-indices in combinations_with_replacement order:
  ! choose p variable slots v(1)<=v(2)<=...<=v(p); alpha(i) = #{slots==i}
  SUBROUTINE gen_cwr( D0, p, list, nmax, icount )
    implicit none
    integer,intent(IN) :: D0, p, nmax
    integer,intent(INOUT) :: list(D0,nmax), icount
    integer :: slots(max(p,1))
    if ( p == 0 ) then
       if ( icount >= nmax ) then
          write(*,*) "gen_cwr: the enumeration exceeds the counted size", nmax
          stop
       end if
       icount = icount+1
       list(:,icount) = 0
       return
    end if
    call cwr_rec( D0, p, 1, 1, slots, list, nmax, icount )
  END SUBROUTINE gen_cwr

  RECURSIVE SUBROUTINE cwr_rec( D0, p, depth, vmin, slots, list, nmax, icount )
    implicit none
    integer,intent(IN) :: D0, p, depth, vmin, nmax
    integer,intent(INOUT) :: slots(p), list(D0,nmax), icount
    integer :: v, i
    do v=vmin,D0
       slots(depth) = v
       if ( depth == p ) then
          if ( icount >= nmax ) then
             write(*,*) "cwr_rec: the enumeration exceeds the counted size", nmax
             write(*,*) "  (n_multi_indices and gen_cwr disagree)"
             stop
          end if
          icount = icount+1
          list(:,icount) = 0
          do i=1,p
             list(slots(i),icount) = list(slots(i),icount) + 1
          end do
       else
          call cwr_rec( D0, p, depth+1, v, slots, list, nmax, icount )
       end if
    end do
  END SUBROUTINE cwr_rec

  !=====================================================================
  !> Snapshot the tables built by the most recent init_hod_tables call.
  SUBROUTINE tabset_from_current( ts )
    implicit none
    type(tabset_t),intent(OUT) :: ts
    if ( .not. hod_tables_ready ) then
       write(*,*) "tabset_from_current: call init_hod_tables first"
       stop
    end if
    ts%d0 = HOD_D0;  ts%kmax = HOD_KMAX;  ts%na = NUM_alpha
    ! Plain Fortran 90 deep copies (allocate to the source shape, keeping
    ! the nonzero lower bounds of tpc and fq_start, then assign).
    allocate( ts%alpha_list(size(alpha_list,1),size(alpha_list,2)) )
    ts%alpha_list = alpha_list
    allocate( ts%alpha_deg(size(alpha_deg)) );    ts%alpha_deg = alpha_deg
    allocate( ts%ind_e1(size(ind_e1)) );          ts%ind_e1 = ind_e1
    allocate( ts%pair_start(size(pair_start)) );  ts%pair_start = pair_start
    allocate( ts%pair_num(size(pair_num)) );      ts%pair_num = pair_num
    allocate( ts%pair_ia(size(pair_ia)) );        ts%pair_ia = pair_ia
    allocate( ts%pair_id(size(pair_id)) );        ts%pair_id = pair_id
    allocate( ts%pair_binom(size(pair_binom)) );  ts%pair_binom = pair_binom
    allocate( ts%fq_start(lbound(fq_start,1):ubound(fq_start,1), &
                          lbound(fq_start,2):ubound(fq_start,2)) )
    ts%fq_start = fq_start
    allocate( ts%fq_num(lbound(fq_num,1):ubound(fq_num,1), &
                        lbound(fq_num,2):ubound(fq_num,2)) )
    ts%fq_num = fq_num
    allocate( ts%fq_ib(size(fq_ib)) );            ts%fq_ib = fq_ib
    allocate( ts%fq_id(size(fq_id)) );            ts%fq_id = fq_id
    allocate( ts%fq_c(size(fq_c)) );              ts%fq_c = fq_c
    allocate( ts%tpc(0:ubound(tanh_pc,1), 0:ubound(tanh_pc,2)) )
    ts%tpc = tanh_pc
  END SUBROUTINE tabset_from_current

  !> Release a table set.  Needed because a net_t carries its own deep
  !! copy of the tables, which for a force-field sized set is far larger
  !! than the weights themselves.
  !> Release the module-level tables and mark them unbuilt, so that a
  !! host can call init_hod_tables again with a different D0, K or seed
  !! set.  Idempotent: safe before any build and safe twice.
  SUBROUTINE reset_hod_tables
    implicit none
    if ( allocated(alpha_list) ) deallocate( alpha_list )
    if ( allocated(alpha_deg) ) deallocate( alpha_deg )
    if ( allocated(ind_e1) ) deallocate( ind_e1 )
    if ( allocated(ind_diff) ) deallocate( ind_diff )
    if ( allocated(binom_ab) ) deallocate( binom_ab )
    if ( allocated(pair_start) ) &
         deallocate( pair_start,pair_num,pair_ia,pair_id,pair_binom )
    if ( allocated(fq_start) ) deallocate( fq_start,fq_num,fq_ib,fq_id,fq_c )
    if ( allocated(bell_num) ) &
         deallocate( bell_num, bell_start, bell_coef, bell_part )
    if ( allocated(tanh_pc) ) deallocate( tanh_pc )
    if ( allocated(lex_ord) ) deallocate( lex_ord )
    HOD_D0 = 0;  HOD_KMAX = 0;  NUM_alpha = 0
    hod_tables_ready = .false.
  END SUBROUTINE reset_hod_tables

  SUBROUTINE tabset_free( ts )
    implicit none
    type(tabset_t),intent(INOUT) :: ts
    if ( allocated(  ts%alpha_list) ) deallocate( ts%alpha_list )
    if ( allocated(  ts%alpha_deg) )  deallocate( ts%alpha_deg )
    if ( allocated(  ts%ind_e1) )     deallocate( ts%ind_e1 )
    if ( allocated(  ts%pair_start) ) deallocate( ts%pair_start, ts%pair_num, &
                                                ts%pair_ia, ts%pair_id, ts%pair_binom )
    if ( allocated(  ts%fq_start) )   deallocate( ts%fq_start, ts%fq_num, &
                                                ts%fq_ib, ts%fq_id, ts%fq_c )
    if ( allocated(  ts%tpc) )        deallocate( ts%tpc )
    ts%d0 = 0;  ts%kmax = 0;  ts%na = 0
  END SUBROUTINE tabset_free

  !> Build an independent table set.  The module level tables end up
  !! holding the set built last; every tabset keeps its own deep copy,
  !! so the build order does not matter to the sets themselves.
  SUBROUTINE tabset_init( ts, D0, K, nseed, seed_alpha )
    implicit none
    type(tabset_t),intent(OUT) :: ts
    integer,intent(IN) :: D0, K, nseed
    integer,intent(IN) :: seed_alpha(D0,*)
    call init_hod_tables( D0, K, nseed, seed_alpha )
    call tabset_from_current( ts )
  END SUBROUTINE tabset_init

  !> d(q) = sigma^{(q)}(a) for q=0..nq, on the polynomials of one set.
  !> sigma^(q)(a) for q = 0..nq, for the activation the table set carries.
  !!
  !! Everything downstream of this routine (the Bell recursion, the
  !! adjoint, the closure) consumes only this vector, so an activation is
  !! added here and nowhere else.
  !!
  !!   tanh  d(q) = P_q(t), t = tanh a, from the stored polynomial table
  !!   sin   d(q) = sin(a + q pi/2), exact and bounded by one at every
  !!         order, which is why it is attractive at large K
  !!   erf   d(q) = (2/sqrt(pi)) (-1)^(q-1) H_{q-1}(a) exp(-a^2) for
  !!         q >= 1, carried as the Hermite functions psi_n = H_n exp(-a^2)
  !!         by psi_{n+1} = 2a psi_n - 2n psi_{n-1}, so the polynomial is
  !!         never formed on its own

  !> erf without the Fortran 2008 intrinsic, so that the strict Fortran 95
  !! build keeps working.  Series below 2 and continued fraction above,
  !! which is the standard split and gives full double precision.

  !> sigma^(q)(a) for q = 0..nq, for whichever activation the table set
  !! carries.  This is the whole of the activation contract: every
  !! recursion downstream sees only this vector.
  SUBROUTINE act_derivs_ts( ts, a, nq, d )
    implicit none
    type(tabset_t),intent(IN) :: ts
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    select case ( ts%iact )
    case ( 1 )
       call sin_derivs( a, nq, d )
    case ( 2 )
       call erf_derivs( a, nq, d )
    case ( 3 )
       call besj0_derivs( a, nq, d )
    case ( 4 )
       call besj1_derivs( a, nq, d )
    case default
       call tanh_derivs_ts( ts, a, nq, d )
    end select
  END SUBROUTINE act_derivs_ts

  !> sin: every derivative is a phase shift, so all orders are bounded by
  !! one.  No table and no recursion are needed.
  SUBROUTINE sin_derivs( a, nq, d )
    implicit none
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8),parameter :: pio2 = 1.57079632679489661923d0
    integer :: q
    do q=0,nq
       d(q) = sin( a + dble(q)*pio2 )
    end do
  END SUBROUTINE sin_derivs

  !> J_0: every derivative is a fixed binomial combination of Bessel
  !! functions,
  !!   J_0^(q)(a) = ((-1)^q / 2^q) sum_(k=0..q) (-1)^k C(q,k) J_(q-2k)(a),
  !! with J_(-n) = (-1)^n J_n.  Since |J_n| <= 1 for every order and every
  !! real argument, the whole sequence is bounded by one, and it needs a
  !! single call returning J_0..J_q.  There is no singularity and no
  !! branch: the origin is an ordinary point.
  SUBROUTINE besj0_derivs( a, nq, d )
    use bessel_module, only: besj_series
    implicit none
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8) :: bj(0:nq), c, term
    integer :: q, k, m
    call besj_series( nq, a, bj )
    do q=0,nq
       term = 0.d0
       c = 1.d0                       ! C(q,0)
       do k=0,q
          m = q - 2*k
          if ( m >= 0 ) then
             term = term + ( (-1.d0)**k )*c*bj(m)
          else
             ! J_(-n) = (-1)^n J_n
             term = term + ( (-1.d0)**k )*c*( (-1.d0)**(-m) )*bj(-m)
          end if
          c = c*dble(q-k)/dble(k+1)   ! C(q,k+1) from C(q,k)
       end do
       d(q) = ( (-1.d0)**q )*term/( 2.d0**q )
    end do
  END SUBROUTINE besj0_derivs

  !> J_1, the odd sibling of J_0.
  !!
  !! J_0 is even, so a layer cannot tell the sign of its pre-activation
  !! and half of the representable functions are lost at every depth.
  !! J_1 is odd and keeps the same derivative structure: the same
  !! binomial rule shifted by one order,
  !!   J_1^(q)(a) = (1/2^q) sum_(k=0..q) (-1)^k C(q,k) J_(1+q-2k)(a),
  !! so it is bounded by one at every order as well.  Measured on
  !! [-6,6] the maxima are 0.58, 0.41, 0.33, 0.29, 0.26 at q = 0,2,4,6,8,
  !! against 1220 for tanh and 1 for sin.
  SUBROUTINE besj1_derivs( a, nq, d )
    use bessel_module, only: besj_series
    implicit none
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8) :: bj(0:nq+1), c, term
    integer :: q, k, m
    call besj_series( nq+1, a, bj )
    do q=0,nq
       term = 0.d0
       c = 1.d0
       do k=0,q
          m = 1 + q - 2*k
          if ( m >= 0 ) then
             term = term + ( (-1.d0)**k )*c*bj(m)
          else
             term = term + ( (-1.d0)**k )*c*( (-1.d0)**(-m) )*bj(-m)
          end if
          c = c*dble(q-k)/dble(k+1)
       end do
       d(q) = ( (-1.d0)**q )*term/( 2.d0**q )
    end do
  END SUBROUTINE besj1_derivs

  !> erf: the derivatives are the Hermite functions,
  !!   erf^(q)(a) = (2/sqrt(pi)) (-1)^(q-1) H_(q-1)(a) exp(-a^2),
  !! carried by the three-term recurrence on psi_n = H_n exp(-a^2),
  !!   psi_0 = exp(-a^2), psi_1 = 2 a psi_0,
  !!   psi_(n+1) = 2 a psi_n - 2 n psi_(n-1),
  !! which never forms the bare polynomial and so cannot overflow.
  SUBROUTINE erf_derivs( a, nq, d )
    use erf_value_module, only: erf_value
    implicit none
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8),parameter :: c2spi = 1.12837916709551257390d0   ! 2/sqrt(pi)
    real(8) :: psi(0:nq+1)
    integer :: q, n
    d(0) = erf_value( a )
    if ( nq < 1 ) return
    psi(0) = exp( -a*a )
    psi(1) = 2.d0*a*psi(0)
    do n=1,nq-1
       psi(n+1) = 2.d0*a*psi(n) - 2.d0*dble(n)*psi(n-1)
    end do
    do q=1,nq
       d(q) = c2spi*( (-1.d0)**(q-1) )*psi(q-1)
    end do
  END SUBROUTINE erf_derivs

  SUBROUTINE tanh_derivs_ts( ts, a, nq, d )
    implicit none
    type(tabset_t),intent(IN) :: ts
    real(8),intent(IN) :: a
    integer,intent(IN) :: nq
    real(8),intent(OUT) :: d(0:nq)
    real(8) :: t
    integer :: q, i
    t = tanh(a)
    do q=0,nq
       d(q) = ts%tpc(q+1,q)
       do i=q,0,-1
          d(q) = d(q)*t + ts%tpc(i,q)
       end do
    end do
  END SUBROUTINE tanh_derivs_ts

END MODULE multi_index_bell_module
